---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:6.2.5
  amd64: ghcr.io/hassio-addons/debian-base:6.2.5
  armv7: ghcr.io/hassio-addons/debian-base:6.2.5
codenotary:
  signer: deepaksrivastav@gmail.com