---
name: WebDAV (powered by rclone)
version: dev
slug: webdav
description: An rclone powered WebDAV server
url: https://github.com/deepaksrivastav/webdav-addon
codenotary: deepaksrivastav@gmail.com
webui: "[PROTO:ssl]://[HOST]:[PORT:8765]"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8765/tcp: 8765
ports_description:
  8765/tcp: WebDAV web interface
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  username: webdav
  password: initpass
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  username: str
  password: str